-- Portal J3K Seguro — esquema inicial Supabase
-- Ejecutar en Supabase SQL Editor.

create extension if not exists pgcrypto;

do $$ begin
  create type public.j3k_role as enum ('admin', 'contador', 'rrhh', 'consulta');
exception
  when duplicate_object then null;
end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  display_name text,
  role public.j3k_role not null default 'consulta',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.modules (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  category text not null,
  route text,
  description text,
  is_active boolean not null default true,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.documents_generated (
  id uuid primary key default gen_random_uuid(),
  module_name text not null,
  category text not null,
  title text not null,
  status text not null default 'registrado',
  payload jsonb not null default '{}'::jsonb,
  version integer not null default 1,
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.purchases (
  id uuid primary key default gen_random_uuid(),
  document_id uuid references public.documents_generated(id) on delete cascade,
  supplier text not null,
  concept text not null,
  amount numeric(14,2) not null default 0,
  currency text not null default 'PEN',
  issue_date date,
  notes text,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.sales (
  id uuid primary key default gen_random_uuid(),
  document_id uuid references public.documents_generated(id) on delete cascade,
  customer text not null,
  concept text not null,
  amount numeric(14,2) not null default 0,
  currency text not null default 'PEN',
  issue_date date,
  notes text,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.hr_records (
  id uuid primary key default gen_random_uuid(),
  document_id uuid references public.documents_generated(id) on delete cascade,
  employee_name text not null,
  record_type text not null,
  amount numeric(14,2) not null default 0,
  issue_date date,
  notes text,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.zip_archives (
  id uuid primary key default gen_random_uuid(),
  document_id uuid references public.documents_generated(id) on delete set null,
  category text not null,
  file_name text not null,
  storage_bucket text not null default 'j3k-archivos',
  storage_path text not null,
  mime_type text,
  size_bytes bigint,
  version integer not null default 1,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id),
  action text not null,
  table_name text,
  record_id text,
  module_name text,
  old_data jsonb,
  new_data jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.current_user_role()
returns text
language sql
security definer
set search_path = public
as $$
  select role::text from public.profiles where id = auth.uid()
$$;

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select coalesce((select role = 'admin' from public.profiles where id = auth.uid()), false)
$$;

create or replace function public.can_access_category(category_text text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  r text;
  c text;
begin
  select public.current_user_role() into r;
  c := lower(coalesce(category_text, ''));

  if r = 'admin' then
    return true;
  end if;

  if r = 'contador' and c in ('compras', 'ventas', 'contabilidad', 'acuerdos', 'otros', 'bitacora', 'bitácora') then
    return true;
  end if;

  if r = 'rrhh' and c in ('rrhh', 'rh', 'recursos humanos') then
    return true;
  end if;

  if r = 'consulta' then
    return true;
  end if;

  return false;
end
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, display_name, role)
  values (new.id, new.email, coalesce(new.raw_user_meta_data->>'display_name', new.email), 'consulta')
  on conflict (id) do nothing;
  return new;
end
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end
$$;

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists set_modules_updated_at on public.modules;
create trigger set_modules_updated_at
before update on public.modules
for each row execute function public.set_updated_at();

drop trigger if exists set_documents_updated_at on public.documents_generated;
create trigger set_documents_updated_at
before update on public.documents_generated
for each row execute function public.set_updated_at();

create or replace function public.audit_row_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  record_uuid text;
  mod_name text;
begin
  if tg_op = 'DELETE' then
    record_uuid := old.id::text;
    mod_name := coalesce(old.module_name, old.category, tg_table_name);
    insert into public.audit_logs(actor_id, action, table_name, record_id, module_name, old_data, new_data)
    values (auth.uid(), tg_op, tg_table_name, record_uuid, mod_name, to_jsonb(old), null);
    return old;
  else
    record_uuid := new.id::text;
    mod_name := coalesce(new.module_name, new.category, tg_table_name);
    insert into public.audit_logs(actor_id, action, table_name, record_id, module_name, old_data, new_data)
    values (auth.uid(), tg_op, tg_table_name, record_uuid, mod_name, case when tg_op='UPDATE' then to_jsonb(old) else null end, to_jsonb(new));
    return new;
  end if;
end
$$;

drop trigger if exists audit_documents_generated on public.documents_generated;
create trigger audit_documents_generated
after insert or update or delete on public.documents_generated
for each row execute function public.audit_row_change();

drop trigger if exists audit_zip_archives on public.zip_archives;
create trigger audit_zip_archives
after insert or update or delete on public.zip_archives
for each row execute function public.audit_row_change();

drop trigger if exists audit_modules on public.modules;
create trigger audit_modules
after insert or update or delete on public.modules
for each row execute function public.audit_row_change();

alter table public.profiles enable row level security;
alter table public.modules enable row level security;
alter table public.documents_generated enable row level security;
alter table public.purchases enable row level security;
alter table public.sales enable row level security;
alter table public.hr_records enable row level security;
alter table public.zip_archives enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists "profiles_read_own_or_admin" on public.profiles;
create policy "profiles_read_own_or_admin"
on public.profiles for select to authenticated
using (id = auth.uid() or public.is_admin());

drop policy if exists "profiles_update_own_or_admin" on public.profiles;
create policy "profiles_update_own_or_admin"
on public.profiles for update to authenticated
using (id = auth.uid() or public.is_admin())
with check (id = auth.uid() or public.is_admin());

drop policy if exists "modules_read_authenticated" on public.modules;
create policy "modules_read_authenticated"
on public.modules for select to authenticated
using (is_active = true or public.is_admin());

drop policy if exists "modules_admin_insert" on public.modules;
create policy "modules_admin_insert"
on public.modules for insert to authenticated
with check (public.is_admin());

drop policy if exists "modules_admin_update" on public.modules;
create policy "modules_admin_update"
on public.modules for update to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "documents_read_allowed" on public.documents_generated;
create policy "documents_read_allowed"
on public.documents_generated for select to authenticated
using (public.can_access_category(category));

drop policy if exists "documents_insert_allowed" on public.documents_generated;
create policy "documents_insert_allowed"
on public.documents_generated for insert to authenticated
with check (public.current_user_role() in ('admin','contador','rrhh') and public.can_access_category(category));

drop policy if exists "documents_update_allowed" on public.documents_generated;
create policy "documents_update_allowed"
on public.documents_generated for update to authenticated
using (public.is_admin() or created_by = auth.uid())
with check (public.is_admin() or created_by = auth.uid());

drop policy if exists "purchases_all_contador_admin" on public.purchases;
create policy "purchases_all_contador_admin"
on public.purchases for all to authenticated
using (public.current_user_role() in ('admin','contador'))
with check (public.current_user_role() in ('admin','contador'));

drop policy if exists "sales_all_contador_admin" on public.sales;
create policy "sales_all_contador_admin"
on public.sales for all to authenticated
using (public.current_user_role() in ('admin','contador'))
with check (public.current_user_role() in ('admin','contador'));

drop policy if exists "hr_all_rrhh_admin" on public.hr_records;
create policy "hr_all_rrhh_admin"
on public.hr_records for all to authenticated
using (public.current_user_role() in ('admin','rrhh'))
with check (public.current_user_role() in ('admin','rrhh'));

drop policy if exists "zip_read_allowed" on public.zip_archives;
create policy "zip_read_allowed"
on public.zip_archives for select to authenticated
using (public.can_access_category(category));

drop policy if exists "zip_insert_allowed" on public.zip_archives;
create policy "zip_insert_allowed"
on public.zip_archives for insert to authenticated
with check (public.current_user_role() in ('admin','contador','rrhh') and public.can_access_category(category));

drop policy if exists "audit_read_admin" on public.audit_logs;
create policy "audit_read_admin"
on public.audit_logs for select to authenticated
using (public.is_admin());

insert into public.modules (name, category, route, description)
values
  ('Compras', 'compras', '/compras', 'Registro de compras con historial y archivos.'),
  ('Ventas', 'ventas', '/ventas', 'Registro de ventas con historial y archivos.'),
  ('RRHH', 'rrhh', '/rrhh', 'Registros laborales, boletas y expedientes.'),
  ('Acuerdos', 'acuerdos', '/acuerdos', 'Actas, contratos y documentos de acuerdos.'),
  ('Bitácora Vehicular', 'otros', '/bitacora', 'Control mensual vehicular.'),
  ('Agregar módulo futuro', 'admin', '/modulos', 'Alta de nuevos módulos y categoría destino.');
